-- AISO MVP 0.1 schema. Business identifiers (Resource_ID, Operation_ID, ...) are the primary keys.

CREATE TABLE app_user (
    id                   VARCHAR(64)  PRIMARY KEY,
    full_name            VARCHAR(200) NOT NULL,
    user_role            VARCHAR(20)  NOT NULL,
    messenger_id         VARCHAR(100),
    active               BOOLEAN      NOT NULL,
    contact_info         VARCHAR(300),
    password_hash        VARCHAR(100) NOT NULL,
    must_change_password BOOLEAN      NOT NULL,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE work_resource (
    id                  VARCHAR(64)  PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    resource_type       VARCHAR(100),
    responsible_user_id VARCHAR(64) REFERENCES app_user (id),
    capacity            INTEGER      NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    description         VARCHAR(1000)
);

CREATE TABLE item (
    id                   VARCHAR(64)  PRIMARY KEY,
    name                 VARCHAR(200) NOT NULL,
    quantity             DOUBLE PRECISION NOT NULL,
    unit                 VARCHAR(30),
    supply_type          VARCHAR(50),
    related_operation_id VARCHAR(64),
    description          VARCHAR(1000)
);

CREATE TABLE operation (
    id                  VARCHAR(64)  PRIMARY KEY,
    name                VARCHAR(300) NOT NULL,
    item_id             VARCHAR(64) REFERENCES item (id),
    resource_id         VARCHAR(64)  NOT NULL REFERENCES work_resource (id),
    responsible_user_id VARCHAR(64) REFERENCES app_user (id),
    preparation_time    DOUBLE PRECISION NOT NULL,
    transport_time      DOUBLE PRECISION NOT NULL,
    setup_time          DOUBLE PRECISION NOT NULL,
    direct_time         DOUBLE PRECISION NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    assigned_user_id    VARCHAR(64) REFERENCES app_user (id),
    block_reason        VARCHAR(1000),
    status_before_block VARCHAR(20),
    progress_percent    INTEGER      NOT NULL,
    planned_start       TIMESTAMP WITH TIME ZONE,
    planned_end         TIMESTAMP WITH TIME ZONE,
    assigned_at         TIMESTAMP WITH TIME ZONE,
    started_at          TIMESTAMP WITH TIME ZONE,
    completed_at        TIMESTAMP WITH TIME ZONE,
    completion_approved BOOLEAN      NOT NULL,
    completion_approved_by VARCHAR(64),
    cancel_reason       VARCHAR(1000),
    description         VARCHAR(1000),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    version             BIGINT       NOT NULL
);
CREATE INDEX idx_operation_status ON operation (status);
CREATE INDEX idx_operation_assigned ON operation (assigned_user_id);

CREATE TABLE predecessor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id    VARCHAR(64)  NOT NULL REFERENCES operation (id),
    predecessor_id  VARCHAR(64)  NOT NULL REFERENCES operation (id),
    dependency_type VARCHAR(20)  NOT NULL,
    start_condition VARCHAR(300),
    mandatory       BOOLEAN      NOT NULL,
    description     VARCHAR(500),
    CONSTRAINT uq_predecessor UNIQUE (operation_id, predecessor_id)
);

CREATE TABLE system_setting (
    id                          INTEGER PRIMARY KEY,
    project_id                  VARCHAR(64),
    project_name                VARCHAR(200),
    owner_id                    VARCHAR(64),
    manager_id                  VARCHAR(64),
    messenger_platform          VARCHAR(30)  NOT NULL,
    system_status               VARCHAR(20)  NOT NULL,
    data_version                VARCHAR(50),
    configuration_version       INTEGER      NOT NULL,
    assignment_mode             VARCHAR(20)  NOT NULL,
    max_active_tasks_per_user   INTEGER      NOT NULL,
    require_completion_approval BOOLEAN      NOT NULL,
    updated_at                  TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO system_setting (id, project_id, project_name, messenger_platform, system_status, data_version,
                            configuration_version, assignment_mode, max_active_tasks_per_user,
                            require_completion_approval, updated_at)
VALUES (1, 'P-001', 'AISO Project', 'IN_APP', 'ACTIVE', '0', 1, 'ALGORITHM', 3, FALSE, CURRENT_TIMESTAMP);

CREATE TABLE audit_event (
    event_id       VARCHAR(36)  PRIMARY KEY,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_id       VARCHAR(64),
    action_name    VARCHAR(60)  NOT NULL,
    entity_type    VARCHAR(60)  NOT NULL,
    entity_id      VARCHAR(64),
    previous_value VARCHAR(4000),
    new_value      VARCHAR(4000),
    reason         VARCHAR(1000),
    project_id     VARCHAR(64)
);
CREATE INDEX idx_audit_time ON audit_event (occurred_at);
CREATE INDEX idx_audit_entity ON audit_event (entity_type, entity_id);

CREATE TABLE notification (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id         VARCHAR(64)  NOT NULL REFERENCES app_user (id),
    kind                 VARCHAR(40)  NOT NULL,
    message              VARCHAR(1000) NOT NULL,
    related_operation_id VARCHAR(64),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    read_at              TIMESTAMP WITH TIME ZONE,
    delivery_status      VARCHAR(20)  NOT NULL,
    delivery_error       VARCHAR(500)
);
CREATE INDEX idx_notification_recipient ON notification (recipient_id, created_at);

CREATE TABLE operation_report (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id     VARCHAR(64)  NOT NULL REFERENCES operation (id),
    user_id          VARCHAR(64)  NOT NULL,
    report_type      VARCHAR(30)  NOT NULL,
    progress_percent INTEGER,
    note             VARCHAR(2000),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_report_operation ON operation_report (operation_id);

CREATE TABLE assignment_run (
    id             VARCHAR(36)  PRIMARY KEY,
    requested_mode VARCHAR(20)  NOT NULL,
    effective_mode VARCHAR(20)  NOT NULL,
    fallback       BOOLEAN      NOT NULL,
    model          VARCHAR(100),
    summary        VARCHAR(2000),
    warnings       VARCHAR(4000),
    unassigned     VARCHAR(4000),
    requested_by   VARCHAR(64)  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_ms    BIGINT       NOT NULL,
    input_tokens   BIGINT,
    output_tokens  BIGINT
);

CREATE TABLE assignment_proposal (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id        VARCHAR(36)  NOT NULL REFERENCES assignment_run (id),
    operation_id  VARCHAR(64)  NOT NULL REFERENCES operation (id),
    user_id       VARCHAR(64)  NOT NULL REFERENCES app_user (id),
    source        VARCHAR(20)  NOT NULL,
    reason        VARCHAR(2000),
    planned_start TIMESTAMP WITH TIME ZONE,
    planned_end   TIMESTAMP WITH TIME ZONE,
    status        VARCHAR(20)  NOT NULL,
    decision_note VARCHAR(500),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_at    TIMESTAMP WITH TIME ZONE,
    decided_by    VARCHAR(64)
);
CREATE INDEX idx_proposal_status ON assignment_proposal (status);

CREATE TABLE import_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_id     VARCHAR(64)  NOT NULL,
    file_name    VARCHAR(300),
    file_format  VARCHAR(20),
    status       VARCHAR(20)  NOT NULL,
    error_count  INTEGER      NOT NULL,
    summary      VARCHAR(2000),
    details      VARCHAR(9000)
);
